spring:
  datasource:
    url: jdbc:mysql://localhost:3306/securityProject?useUnicode=true&charaterEncoding=utf-8
    username: security
    password: security
    driver-class-name: com.mysql.jdbc.Driver